# Generated by Django 5.0.6 on 2024-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productoDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Precio')),
                ('descripcion', models.TextField(max_length=75, verbose_name='Descripcion')),
                ('proveedor', models.CharField(blank=True, max_length=40, null=True, verbose_name='Proveedor')),
                ('imagen', models.TextField(blank=True, max_length=120, null=True, verbose_name='Imagen')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha_entrega')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido')),
                ('fecha_venta', models.DateField(blank=True, null=True, verbose_name='Fecha_venta')),
                ('codigo', models.IntegerField(default=0, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
